# Site settings
title: Hyde
email: bstevensondev@gmail.com
description: A website for Hyde editor
owner:
  name: Brett Stevenson # or company name
  url: http://brettstevenson.io
repo: https://github.com/JonSn0w/Hyde
bugs: https://github.com/JonSn0w/Hyde/issues/new
first_published: 2017
baseurl: "/Hyde/" # the subpath of your site, e.g. /blog/

url: "" # the base hostname & protocol for your site
twitter_username: bstevensondev
github_username:  JonSn0w

name: 'Brett Stevenson'
author: 'Brett Stevenson'
favicon: /images/favicon.png

# Build settings
markdown: kramdown
highlighter: rouge
sass:
 style: compressed

# Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"


exclude: ['template.md', '.gitignore', 'TODO.md', 'README.md', 'Gulpfile.js', 'package.json', 'node_modules', 'jspm_packages']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page

gems:
  - jekyll-paginate
